#!/usr/bin/env node
/**
 * CUBE CSS pipeline:
 * 1. Copy layer sources from src/web/styles/ → src/web/public/
 * 2. Concatenate colocated *.css under src/web (excluding public, tokens, styles)
 *    into src/web/public/blocks.css
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.join(__dirname, "..");
const WEB_ROOT = path.join(APP_ROOT, "src/web");
const STYLES_DIR = path.join(WEB_ROOT, "styles");
const PUBLIC_DIR = path.join(WEB_ROOT, "public");

const LAYER_FILES = ["globals.css", "compositions.css", "utilities.css"];

function die(message) {
  console.error(message);
  process.exit(1);
}

/** @param {string} dir */
function collectCssFilesRecursive(dir) {
  /** @type {string[]} */
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) out.push(...collectCssFilesRecursive(p));
    else if (ent.isFile() && ent.name.endsWith(".css")) out.push(p);
  }
  return out;
}

function shouldIncludeBlockCss(absPath) {
  const rel = path.relative(WEB_ROOT, absPath);
  const segments = rel.split(path.sep);
  if (segments[0] === "public") return false;
  if (segments[0] === "tokens") return false;
  if (segments[0] === "styles") return false;
  return true;
}

function main() {
  fs.mkdirSync(PUBLIC_DIR, { recursive: true });

  for (const name of LAYER_FILES) {
    const src = path.join(STYLES_DIR, name);
    if (!fs.existsSync(src)) die(`Missing layer file: ${src}`);
    const dest = path.join(PUBLIC_DIR, name);
    fs.copyFileSync(src, dest);
    console.error("Copied", path.relative(APP_ROOT, dest));
  }

  const allCss = collectCssFilesRecursive(WEB_ROOT);
  const blockSources = allCss.filter(shouldIncludeBlockCss).sort((a, b) => a.localeCompare(b));

  const blocksLines = [];
  blocksLines.push("/**");
  blocksLines.push(" * CUBE — block + exception CSS (colocated sources concatenated).");
  blocksLines.push(" * Generated by scripts/build-web-css.mjs — do not edit by hand.");
  blocksLines.push(" */");
  blocksLines.push("");

  for (const abs of blockSources) {
    const relWeb = path.relative(WEB_ROOT, abs).split(path.sep).join("/");
    blocksLines.push(`/* ndb2:block: ${relWeb} */`);
    blocksLines.push(fs.readFileSync(abs, "utf8").trimEnd());
    blocksLines.push("");
  }

  const blocksPath = path.join(PUBLIC_DIR, "blocks.css");
  fs.writeFileSync(blocksPath, `${blocksLines.join("\n").trimEnd()}\n`, "utf8");
  console.error("Wrote", path.relative(APP_ROOT, blocksPath), `(${blockSources.length} source file(s))`);
}

main();
